"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import html2canvas from "html2canvas";

type RecapMode = "team" | "rep";

type RecapData = {
  label: string;
  metaLeft: string;
  metaRight: string;
  statement: string;
  rows: Array<[string, string]>;
  footer: string;
};

const RECAP_DATA: Record<RecapMode, RecapData> = {
  team: {
    label: "Team DACH",
    metaLeft: "Numi Sales Recap / May 2026",
    metaRight: "DACH TEAM",
    statement: "Top reps held price discipline in 82% of late-stage calls.",
    rows: [
      ["Best handled objections", "Too expensive / Competitor in place / No budget"],
      ["Strongest team behavior", "Value was anchored before pricing was discussed"],
      ["Social proof line", "DACH reps converted pressure into qualified next steps."]
    ],
    footer: "Generated by Numi Anti-Sycophant Engine"
  },
  rep: {
    label: "Individual Rep",
    metaLeft: "Numi Sales Recap / May 2026",
    metaRight: "Rep-ID: #8402",
    statement: "You ranked #3 in objection control across the DACH team.",
    rows: [
      ["Best handled objections", "Call me next week / We use a competitor / No time"],
      ["Signature behavior", "You held price until pain and urgency were explicit"],
      ["Social proof line", "You turned 11 hesitant calls into qualified next steps."]
    ],
    footer: "Generated by Numi Anti-Sycophant Engine"
  }
};

function scrambleDigits(value: string) {
  return value.replace(/\d/g, () => String(Math.floor(Math.random() * 10)));
}

function TickerText({ value, className = "" }: { value: string; className?: string }) {
  const [displayValue, setDisplayValue] = useState(value);
  const mounted = useRef(false);

  useEffect(() => {
    if (!mounted.current) {
      mounted.current = true;
      setDisplayValue(value);
      return;
    }

    let frame = 0;
    let timeout = 0;
    const maxFrames = 7;

    function tick() {
      frame += 1;
      if (frame >= maxFrames) {
        setDisplayValue(value);
        return;
      }

      setDisplayValue(scrambleDigits(value));
      timeout = window.setTimeout(tick, 24);
    }

    tick();
    return () => window.clearTimeout(timeout);
  }, [value]);

  return <span className={className}>{displayValue}</span>;
}

export default function SalesRecapShareAsset() {
  const [mode, setMode] = useState<RecapMode>("team");
  const [exporting, setExporting] = useState(false);
  const assetRef = useRef<HTMLElement | null>(null);
  const data = RECAP_DATA[mode];

  const filename = useMemo(() => `numi-sales-recap-${mode}.png`, [mode]);

  async function exportPng() {
    if (!assetRef.current || exporting) return;
    setExporting(true);

    try {
      const width = assetRef.current.getBoundingClientRect().width;
      const scale = 1200 / width;
      const canvas = await html2canvas(assetRef.current, {
        backgroundColor: "#ffffff",
        scale,
        width,
        height: width * 1.25,
        useCORS: true
      });

      const link = document.createElement("a");
      link.download = filename;
      link.href = canvas.toDataURL("image/png");
      link.click();
    } finally {
      setExporting(false);
    }
  }

  return (
    <div className="w-full max-w-[480px]">
      <div className="mb-3 flex items-center gap-5 font-mono text-[11px] uppercase tracking-[0.12em] text-black">
        {(Object.keys(RECAP_DATA) as RecapMode[]).map((nextMode) => (
          <button
            key={nextMode}
            type="button"
            className={`p-0 text-left transition-opacity ${
              mode === nextMode ? "opacity-100" : "opacity-35 hover:opacity-70"
            }`}
            onClick={() => setMode(nextMode)}
          >
            [ {RECAP_DATA[nextMode].label} ]
          </button>
        ))}
      </div>

      <article
        ref={assetRef}
        className="numi-share-asset"
        aria-label={`${data.label} Numi Sales Recap`}
      >
        <div className="flex h-full flex-col">
          <div className="border-b border-black pb-4">
            <div className="flex items-start justify-between gap-5 font-mono text-[10px] uppercase leading-4 tracking-[0.12em]">
              <p>{data.metaLeft}</p>
              <p className="text-right">{data.metaRight}</p>
            </div>
          </div>

          <div className="border-b border-black py-8">
            <div className="mb-5 flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.12em]">
              <span className="h-2 w-2 rounded-full bg-[#ff0000] motion-safe:animate-[recap-pulse_1.2s_steps(2,end)_infinite]" />
              <span>Performance KPI</span>
            </div>
            <h3 className="max-w-[390px] text-[34px] font-semibold leading-[1.04] tracking-normal sm:text-[38px]">
              <TickerText value={data.statement} />
            </h3>
          </div>

          <dl className="border-b border-black">
            {data.rows.map(([label, value]) => (
              <div key={label} className="grid grid-cols-[118px_1fr] gap-5 border-b border-black py-4 last:border-b-0">
                <dt className="font-mono text-[10px] uppercase leading-4 tracking-[0.12em]">{label}</dt>
                <dd className="text-[13px] font-medium leading-5">
                  <TickerText value={value} />
                </dd>
              </div>
            ))}
          </dl>

          <div className="mt-auto pt-4">
            <p className="font-mono text-[9px] uppercase leading-4 tracking-[0.12em]">{data.footer}</p>
          </div>
        </div>
      </article>

      <button
        type="button"
        className="mt-3 p-0 font-mono text-[11px] uppercase tracking-[0.12em] text-black opacity-60 transition-opacity hover:opacity-100 disabled:cursor-wait disabled:opacity-35"
        disabled={exporting}
        onClick={exportPng}
      >
        [ {exporting ? "Rendering PNG" : "Export for LinkedIn (PNG)"} ]
      </button>
    </div>
  );
}
